### ISSUE TITLE
Nginx를 통해 HTTPS를 구현한다.

### ISSUE THREAD

**Issue by devFancy** [hibit-team/hibit-backend#8]
## 💁🏻‍♂️ 구현할 기능

> 구현할 기능에 대해 설명해 주세요.

* Nginx를 통해 Https를 구현한다.

## 🎤 세부 작업 내용

* [x] 도메인 구입, Web Server와 연결한다.
* [x] Nginx에 SSL 적용한다.

## 📚참고 자료

* [HTTPS 적용기](https://sokdak-sokdak.tistory.com/7)

**Comment by hyoung01** [comment]
추후 새로운 도메인 주소로 적용 필요 (현재 test용)
